### ISSUE TITLE
Support for TypeDoc 0.26.x?

### ISSUE THREAD

**Issue by jan-molak** [krisztianb/typedoc-plugin-replace-text#11]
Hi @krisztianb and thanks for your work on this plugin; it looks great!

Are you planning to support TypeDoc 0.26.x, please?

**Comment by krisztianb** [comment]
Hi Jan. Thank you. I will update the plugin as soon as I have time. This shouldn't be too difficult.

**Comment by krisztianb** [comment]
I published a new version 4.0.0 on npm which supports only TypeDoc 0.26.x 🎉 

If you were using the `inIncludedFiles` option you will have to update your config - see README for details. Otherwise the plugin should work the same.

Happy testing and please report back if you find any bugs. Thank you.
